// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxjlvdqcltqllxxvyaip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14amx2ZHFjbHRxbGx4eHZ5YWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDIwMzcsImV4cCI6MjA2ODYxODAzN30.sDvxBWdYdlc3GPh4Zj4-tsJMjNH4nf_ZEhur_3IQYVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});